/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provemax34.Vistas;

import java.awt.Color;
import javax.swing.JOptionPane;
import provemax34.AccesoData.ProveedorData;
import provemax34.Entidades.Proveedor;

/**
 *
 * @author Fer
 */
public class AgregarProveedor extends javax.swing.JFrame {
    private Proveedor prov=null;
    private ProveedorData provData=new ProveedorData();
    private Proveedores proveedores=new Proveedores();
    
    public AgregarProveedor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLRazonSocial = new javax.swing.JLabel();
        jLDomicilio = new javax.swing.JLabel();
        jLTelefono = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jTRazonSocial = new javax.swing.JTextField();
        jTDomicilio = new javax.swing.JTextField();
        jTTelefono = new javax.swing.JTextField();
        jCBEstado = new javax.swing.JCheckBox();
        btnAgregarProv = new javax.swing.JPanel();
        txtAgregarProv = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLRazonSocial.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLRazonSocial.setForeground(new java.awt.Color(255, 255, 255));
        jLRazonSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLRazonSocial.setText("Razon Social");
        jPanel1.add(jLRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLDomicilio.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLDomicilio.setForeground(new java.awt.Color(255, 255, 255));
        jLDomicilio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDomicilio.setText("Domicilio");
        jPanel1.add(jLDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLTelefono.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLTelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTelefono.setText("Telefono");
        jPanel1.add(jLTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLEstado.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLEstado.setForeground(new java.awt.Color(255, 255, 255));
        jLEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEstado.setText("Estado");
        jPanel1.add(jLEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jTRazonSocial.setForeground(new java.awt.Color(0, 0, 0));
        jTRazonSocial.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 324, -1));

        jTDomicilio.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 323, -1));

        jTTelefono.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 323, -1));
        jPanel1.add(jCBEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        btnAgregarProv.setBackground(new java.awt.Color(255, 255, 255));

        txtAgregarProv.setBackground(new java.awt.Color(255, 255, 255));
        txtAgregarProv.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtAgregarProv.setForeground(new java.awt.Color(0, 0, 0));
        txtAgregarProv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAgregarProv.setText("Agregar");
        txtAgregarProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAgregarProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAgregarProvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAgregarProvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAgregarProvMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAgregarProvLayout = new javax.swing.GroupLayout(btnAgregarProv);
        btnAgregarProv.setLayout(btnAgregarProvLayout);
        btnAgregarProvLayout.setHorizontalGroup(
            btnAgregarProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarProvLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtAgregarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnAgregarProvLayout.setVerticalGroup(
            btnAgregarProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarProvLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtAgregarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnAgregarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgregarProvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarProvMouseEntered
        btnAgregarProv.setBackground(Color.gray);
    }//GEN-LAST:event_txtAgregarProvMouseEntered

    private void txtAgregarProvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarProvMouseExited
        btnAgregarProv.setBackground(Color.white);
    }//GEN-LAST:event_txtAgregarProvMouseExited

    private void txtAgregarProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarProvMouseClicked
        try {
            String razonSocial = jTRazonSocial.getText();
            String domicilio = jTDomicilio.getText();
            String telefono = jTTelefono.getText();

            if (razonSocial.isEmpty() || domicilio.isEmpty() || telefono.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No puedo haber campos vacios");
                return;
            }
            if (prov == null) {
                prov = new Proveedor(razonSocial, domicilio, telefono, true);
                provData.guardarProveedor(prov);
                limpiarCampos();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Datos incompatible");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Completar datos");
        }
        
    }//GEN-LAST:event_txtAgregarProvMouseClicked

public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAgregarProv;
    private javax.swing.JCheckBox jCBEstado;
    private javax.swing.JLabel jLDomicilio;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLRazonSocial;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTDomicilio;
    private javax.swing.JTextField jTRazonSocial;
    private javax.swing.JTextField jTTelefono;
    private javax.swing.JLabel txtAgregarProv;
    // End of variables declaration//GEN-END:variables

public void limpiarCampos(){
        jTRazonSocial.setText("");
        jTDomicilio.setText("");
        jTTelefono.setText("");
        jCBEstado.setEnabled(false);
        prov=null;
    }
}
