/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provemax34.Vistas;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import provemax34.AccesoData.ProductoData;
import provemax34.Entidades.Producto;

/**
 *
 * @author Fer
 */
public class Menu extends javax.swing.JFrame {
    ArrayList <Producto> listastock;
    private ProductoData pd;
    public Menu() {
        pd=new ProductoData();
        initComponents();
        this.setLocationRelativeTo(null);
        notificaciones();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        txtHome = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelProveedores = new javax.swing.JPanel();
        txtProveedores = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelCompras = new javax.swing.JPanel();
        txtCompras = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelProductos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtProductos1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelDetalleCompra = new javax.swing.JPanel();
        txtDetalleCompra = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelNotificacion = new javax.swing.JPanel();
        txtNotificacion = new javax.swing.JLabel();
        escritorio = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome.setBackground(new java.awt.Color(51, 51, 51));
        panelHome.setForeground(new java.awt.Color(51, 51, 51));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHome.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtHome.setForeground(new java.awt.Color(255, 255, 255));
        txtHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHome.setText("HOME");
        txtHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtHomeMouseExited(evt);
            }
        });
        panelHome.add(txtHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 150, 60));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/provemax34/Imagenes/8666691_home_icon (1).png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelHome.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel2.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 210, 60));

        panelProveedores.setBackground(new java.awt.Color(51, 51, 51));
        panelProveedores.setForeground(new java.awt.Color(51, 51, 51));
        panelProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProveedores.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtProveedores.setForeground(new java.awt.Color(255, 255, 255));
        txtProveedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtProveedores.setText("PROVEEDORES");
        txtProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProveedoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtProveedoresMouseExited(evt);
            }
        });
        panelProveedores.add(txtProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 4, 150, 50));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/provemax34/Imagenes/8666814_truck_transport_icon (1).png"))); // NOI18N
        panelProveedores.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        jPanel2.add(panelProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 60));

        panelCompras.setBackground(new java.awt.Color(51, 51, 51));
        panelCompras.setForeground(new java.awt.Color(51, 51, 51));
        panelCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCompras.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtCompras.setForeground(new java.awt.Color(255, 255, 255));
        txtCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCompras.setText("COMPRAS");
        txtCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtComprasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtComprasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtComprasMouseExited(evt);
            }
        });
        panelCompras.add(txtCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 150, 60));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/provemax34/Imagenes/8666616_shopping_cart_icon (1).png"))); // NOI18N
        panelCompras.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel2.add(panelCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 210, 60));

        panelProductos.setBackground(new java.awt.Color(51, 51, 51));
        panelProductos.setForeground(new java.awt.Color(51, 51, 51));
        panelProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/provemax34/Imagenes/8666822_package_delivery_icon (1).png"))); // NOI18N
        panelProductos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        txtProductos1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtProductos1.setForeground(new java.awt.Color(255, 255, 255));
        txtProductos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtProductos1.setText("PRODUCTOS");
        txtProductos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtProductos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProductos1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtProductos1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtProductos1MouseExited(evt);
            }
        });
        panelProductos.add(txtProductos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 150, 60));

        jPanel2.add(panelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 210, 60));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/provemax34/Imagenes/logo_empresa_pequeño.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 140));

        panelDetalleCompra.setBackground(new java.awt.Color(51, 51, 51));
        panelDetalleCompra.setForeground(new java.awt.Color(51, 51, 51));
        panelDetalleCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDetalleCompra.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtDetalleCompra.setForeground(new java.awt.Color(255, 255, 255));
        txtDetalleCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDetalleCompra.setText("DETALLE COMPRA");
        txtDetalleCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDetalleCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDetalleCompraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDetalleCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDetalleCompraMouseExited(evt);
            }
        });
        panelDetalleCompra.add(txtDetalleCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 150, 60));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/provemax34/Imagenes/8666689_file_text_icon.png"))); // NOI18N
        panelDetalleCompra.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 6, 53, 48));

        jPanel2.add(panelDetalleCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 210, 60));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 540));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNotificacion.setBackground(new java.awt.Color(102, 102, 102));

        txtNotificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNotificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/provemax34/Imagenes/8666714_bell_icon.png"))); // NOI18N
        txtNotificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNotificacionMouseClicked(evt);
            }
        });
        txtNotificacion.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtNotificacionPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout panelNotificacionLayout = new javax.swing.GroupLayout(panelNotificacion);
        panelNotificacion.setLayout(panelNotificacionLayout);
        panelNotificacionLayout.setHorizontalGroup(
            panelNotificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNotificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelNotificacionLayout.setVerticalGroup(
            panelNotificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNotificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.add(panelNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 40, 40));

        background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 780, 110));

        escritorio.setBackground(new java.awt.Color(255, 255, 255));
        escritorio.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        background.add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 780, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHomeMouseEntered
        panelHome.setBackground(Color.gray);
    }//GEN-LAST:event_txtHomeMouseEntered

    private void txtHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHomeMouseExited
        panelHome.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_txtHomeMouseExited

    private void txtProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProveedoresMouseEntered
        panelProveedores.setBackground(Color.gray);
    }//GEN-LAST:event_txtProveedoresMouseEntered

    private void txtProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProveedoresMouseExited
        panelProveedores.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_txtProveedoresMouseExited

    private void txtComprasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtComprasMouseEntered
        panelCompras.setBackground(Color.gray);
    }//GEN-LAST:event_txtComprasMouseEntered

    private void txtComprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtComprasMouseExited
        panelCompras.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_txtComprasMouseExited

    private void txtHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHomeMouseClicked
        escritorio.removeAll();
        escritorio.repaint();
    }//GEN-LAST:event_txtHomeMouseClicked

    private void txtProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProveedoresMouseClicked
        escritorio.removeAll();
        escritorio.repaint();
        Proveedores prov = new Proveedores();
        
        escritorio.add(prov);
        prov.setVisible(true);
    }//GEN-LAST:event_txtProveedoresMouseClicked

    private void txtComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtComprasMouseClicked
        escritorio.removeAll();
        escritorio.repaint();
        Compras comp = new Compras();
        escritorio.add(comp);
        comp.setVisible(true);
    }//GEN-LAST:event_txtComprasMouseClicked

    private void txtProductos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProductos1MouseClicked
        escritorio.removeAll();
        escritorio.repaint();
        Productos prod = new Productos();
        
        escritorio.add(prod);
        prod.setVisible(true);
    }//GEN-LAST:event_txtProductos1MouseClicked

    private void txtProductos1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProductos1MouseEntered
        panelProductos.setBackground(Color.gray);
    }//GEN-LAST:event_txtProductos1MouseEntered

    private void txtProductos1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProductos1MouseExited
        panelProductos.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_txtProductos1MouseExited

    private void txtDetalleCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDetalleCompraMouseEntered
        panelDetalleCompra.setBackground(Color.gray);
    }//GEN-LAST:event_txtDetalleCompraMouseEntered

    private void txtDetalleCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDetalleCompraMouseExited
        panelDetalleCompra.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_txtDetalleCompraMouseExited

    private void txtDetalleCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDetalleCompraMouseClicked
        escritorio.removeAll();
        escritorio.repaint();
        DetallesDeCompras ddc=new DetallesDeCompras();
        escritorio.add(ddc);
        ddc.setVisible(true);
    }//GEN-LAST:event_txtDetalleCompraMouseClicked

    private void txtNotificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNotificacionMouseClicked
        Stock stock = new Stock();
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(stock);
        stock.setVisible(true);
        stock.setLocation(380,0);     
    }//GEN-LAST:event_txtNotificacionMouseClicked

    private void txtNotificacionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtNotificacionPropertyChange

    }//GEN-LAST:event_txtNotificacionPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelCompras;
    private javax.swing.JPanel panelDetalleCompra;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelNotificacion;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel panelProveedores;
    private javax.swing.JLabel txtCompras;
    private javax.swing.JLabel txtDetalleCompra;
    private javax.swing.JLabel txtHome;
    private javax.swing.JLabel txtNotificacion;
    private javax.swing.JLabel txtProductos1;
    private javax.swing.JLabel txtProveedores;
    // End of variables declaration//GEN-END:variables
public void notificaciones(){
        
        listastock=pd.listarProductosPorStockMin();
        if (listastock.isEmpty()) {
           panelNotificacion.setBackground(Color.gray); 
        
    }else{
        
        panelNotificacion.setBackground(Color.red);
        
        Stock stock = new Stock();
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(stock);
        stock.setVisible(true);
        stock.setLocation(380,0);
        }
}
}
